- name: "udpate homebrew"
  community.general.homebrew:
    name: git
    state: latest
    update_homebrew: true

- name: "install homebrew formulae"
  community.general.homebrew:
    name: '{{ homebrew_formulae }}'
    state: latest

- name: "install homebrew casks"
  community.general.homebrew_cask:
    name: '{{ homebrew_casks }}'
    accept_external_apps: true
    state: present
  tags: test